[package]
name = "arxiv-fetch"
version = "0.1.0"
authors = ["cannon <cannon10100@gmail.com>"]

[dependencies]
hyper = "0.11"
futures = "0.1"
tokio-core = "0.1"
lazy_static = "*"
atom_syndication = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

